"""Renderer tests — the markdown report must contain all 20 sections."""

from __future__ import annotations

from pathlib import Path

import pytest

from core.memory import JsonFileMemory
from core.strategy import StrategyPipeline, render_markdown_report

REPO_ROOT = Path(__file__).resolve().parents[2]
DEMO_BRIEF = REPO_ROOT / "examples" / "clients" / "demo-saas" / "brief.json"


@pytest.fixture
def report_markdown(tmp_path: Path) -> str:
    mem = JsonFileMemory(tmp_path)
    pipeline = StrategyPipeline(memory=mem)
    result = pipeline.run_from_path(DEMO_BRIEF)
    return render_markdown_report(result.report)


# ---------- 20 sections present ----------

_SECTION_TITLES = [
    "01. Resumen ejecutivo",
    "02. Diagnóstico del negocio",
    "03. Público objetivo",
    "04. Buyer persona",
    "05. Propuesta de valor",
    "06. Benchmark de competidores",
    "07. Canales recomendados",
    "08. Keywords principales",
    "09. Keywords negativas",
    "10. Hashtags sugeridos",
    "11. Estrategia de campaña",
    "12. Piezas sugeridas",
    "13. Briefs para flyers / imágenes",
    "14. Copies para redes",
    "15. Secuencia de emails",
    "16. Guiones de reels",
    "17. Calendario sugerido",
    "18. Checklist de aprobación",
    "19. Riesgos / claims a validar",
    "20. Próximos pasos",
]


@pytest.mark.parametrize("title", _SECTION_TITLES)
def test_section_header_present(report_markdown: str, title: str) -> None:
    assert f"## {title}" in report_markdown


def test_report_has_top_level_header(report_markdown: str) -> None:
    assert report_markdown.startswith("# Campaign Strategy Report — demo-saas")


def test_report_has_toc(report_markdown: str) -> None:
    assert "## Índice" in report_markdown
    for title in _SECTION_TITLES:
        # TOC has plain title (without `## ` prefix) per section.
        assert title in report_markdown


def test_report_has_footer(report_markdown: str) -> None:
    assert "Generated by `core.strategy` engine v1" in report_markdown


# ---------- content presence ----------

def test_report_contains_objective(report_markdown: str) -> None:
    assert "200 trials" in report_markdown


def test_report_contains_competitor_names(report_markdown: str) -> None:
    assert "Acme Marketing Suite" in report_markdown
    assert "Big SaaS" in report_markdown


def test_report_contains_email_subject_lines(report_markdown: str) -> None:
    assert "Bienvenida a Demo Pro" in report_markdown


def test_report_contains_image_prompts(report_markdown: str) -> None:
    assert "Prompt para image model" in report_markdown


def test_report_contains_approval_checklist_items(report_markdown: str) -> None:
    # Blocker emoji + at least one severity tag.
    assert "🛑" in report_markdown
    assert "[blocker]" in report_markdown
    assert "[must]" in report_markdown


def test_report_contains_schedule_table(report_markdown: str) -> None:
    assert "| Semana | Canal | Pieza | Cadencia |" in report_markdown


def test_report_contains_keyword_clusters(report_markdown: str) -> None:
    assert "Cluster:" in report_markdown


def test_report_is_pure_function_of_report(tmp_path: Path) -> None:
    """Same report instance → same markdown output."""
    mem = JsonFileMemory(tmp_path)
    pipeline = StrategyPipeline(memory=mem)
    result = pipeline.run_from_path(DEMO_BRIEF)
    a = render_markdown_report(result.report)
    b = render_markdown_report(result.report)
    assert a == b
