"""Markdown renderers for the analytics layer (MKT-6A).

Two renderers: one for the import report (post-`mkt import-metrics`)
and one for the recommendation pack (post-`mkt analyze-metrics`).
Both are pure functions.
"""

from __future__ import annotations

from .models import (
    AnalyticsImportReport,
    OptimizationRecommendationPack,
    RecommendationKind,
    RecommendationPriority,
)

_PRIORITY_EMOJI = {"high": "🔴", "medium": "🟠", "low": "⚪"}
_KIND_EMOJI = {
    "repeat": "🔁",
    "pause": "⏸️",
    "improve": "🛠️",
    "seo_opportunity": "🔎",
    "next_action": "➡️",
}


def render_markdown_import_report(report: AnalyticsImportReport) -> str:
    parts: list[str] = []
    parts.append(
        f"# Analytics Import Report — {report.client_slug}\n\n"
        f"- **Import ID**: `{report.import_id}`\n"
        f"- **Contract**: `{report.contract_version}`\n"
        f"- **Source**: `{report.source.value}`\n"
        f"- **File**: `{report.file_path}`\n"
        f"- **Imported**: `{report.imported_at.isoformat()}`\n"
    )
    parts.append("## 01. Resumen")
    parts.append(
        f"- ✅ Filas importadas: `{report.rows_imported}`\n"
        f"- ⚠️ Filas rechazadas: `{report.rows_rejected}`"
    )
    if report.rejected_reasons:
        rejected_lines = ["## 02. Razones de rechazo"]
        for r in report.rejected_reasons:
            rejected_lines.append(f"- {r}")
        parts.append("\n".join(rejected_lines))
    parts.append(
        "---\n\n"
        f"_Generated by `core.analytics.importer` v1 "
        f"(`{report.contract_version}`). Sin API externa. Sin credenciales. "
        "Sin scraping. Solo importación manual local._"
    )
    return "\n\n".join(parts) + "\n"


def render_markdown_recommendations(pack: OptimizationRecommendationPack) -> str:
    parts: list[str] = []
    parts.append(_render_header(pack))
    parts.append(_render_summary(pack))
    parts.append(_render_channels(pack))
    parts.append(_render_content(pack))
    parts.append(_render_seo(pack))
    parts.append(_render_recommendations(pack))
    parts.append(_render_next_actions(pack))
    parts.append(_render_footer(pack))
    return "\n\n".join(parts) + "\n"


def _render_header(pack: OptimizationRecommendationPack) -> str:
    return (
        f"# Optimization Recommendation Pack — {pack.client_slug}\n\n"
        f"- **Pack ID**: `{pack.pack_id}`\n"
        f"- **Contract**: `{pack.contract_version}`\n"
        f"- **Rule set**: `{pack.rule_set_id or '—'}`\n"
        f"- **Snapshot**: `{pack.snapshot_id}` ({pack.snapshot_contract_version})\n"
        f"- **Filas analizadas**: `{pack.total_rows_analyzed}`\n"
        f"- **Generado**: `{pack.created_at.isoformat()}`\n"
    )


def _render_summary(pack: OptimizationRecommendationPack) -> str:
    lines = ["## 01. Resumen"]
    lines.append(f"- 🏆 **Mejor canal**: `{pack.best_channel or '—'}`")
    lines.append(f"- ⏸️ **Peor canal**: `{pack.worst_channel or '—'}`")
    lines.append(f"- 🛠️ **Recomendaciones**: {len(pack.recommendations)}")
    lines.append(
        f"- 🔎 **Oportunidades SEO**: {len(pack.seo_opportunities.opportunities)}"
    )
    return "\n".join(lines)


def _render_channels(pack: OptimizationRecommendationPack) -> str:
    if not pack.channels:
        return "## 02. Canales\n_(sin datos de canal)_"
    lines = ["## 02. Canales (ordenados por clicks + conversions)"]
    lines.append("| # | Canal | Clicks | Impressions | Engagement | Conversions | CTR | Pos. |")
    lines.append("|---|-------|--------|-------------|------------|-------------|-----|------|")
    for i, c in enumerate(pack.channels, start=1):
        ctr = f"{c.avg_ctr:.2%}" if c.avg_ctr is not None else "—"
        pos = f"{c.avg_position:.1f}" if c.avg_position is not None else "—"
        lines.append(
            f"| {i} | `{c.channel}` | {c.total_clicks:.0f} | "
            f"{c.total_impressions:.0f} | {c.total_engagement:.0f} | "
            f"{c.total_conversions:.0f} | {ctr} | {pos} |"
        )
    return "\n".join(lines)


def _render_content(pack: OptimizationRecommendationPack) -> str:
    if not pack.top_content:
        return "## 03. Top content\n_(sin datos por pieza)_"
    lines = ["## 03. Top content"]
    lines.append("| # | Pieza | Canal | Clicks | Engagement | Conversions |")
    lines.append("|---|-------|-------|--------|------------|-------------|")
    for i, c in enumerate(pack.top_content, start=1):
        ref = c.content_ref.replace("|", "\\|")[:60]
        lines.append(
            f"| {i} | `{ref}` | `{c.channel or '—'}` | "
            f"{c.total_clicks:.0f} | {c.total_engagement:.0f} | "
            f"{c.total_conversions:.0f} |"
        )
    return "\n".join(lines)


def _render_seo(pack: OptimizationRecommendationPack) -> str:
    opps = pack.seo_opportunities.opportunities
    if not opps:
        notes = pack.seo_opportunities.notes
        return (
            "## 04. SEO opportunities\n_(sin oportunidades detectadas)_"
            + (f"\n\n> {notes}" if notes else "")
        )
    lines = ["## 04. SEO opportunities"]
    lines.append("| # | Query / Page | Imp. | Clicks | CTR | Pos. | Score | Razón |")
    lines.append("|---|--------------|------|--------|-----|------|-------|-------|")
    for i, o in enumerate(opps, start=1):
        label = (o.query or o.page or "—").replace("|", "\\|")[:50]
        ctr = f"{o.ctr:.1%}" if o.ctr is not None else "—"
        pos = f"{o.position:.1f}" if o.position is not None else "—"
        reason = o.reason.replace("|", "\\|")[:60]
        lines.append(
            f"| {i} | `{label}` | {o.impressions:.0f} | {o.clicks:.0f} | "
            f"{ctr} | {pos} | {o.opportunity_score:.1f} | {reason} |"
        )
    return "\n".join(lines)


def _render_recommendations(pack: OptimizationRecommendationPack) -> str:
    if not pack.recommendations:
        return "## 05. Recomendaciones\n_(sin recomendaciones)_"
    # Sort: priority high → low, then kind.
    rank = {"high": 0, "medium": 1, "low": 2}
    recs = sorted(
        pack.recommendations,
        key=lambda r: (rank.get(r.priority.value, 9), r.kind.value),
    )
    lines = ["## 05. Recomendaciones"]
    for r in recs:
        emoji_p = _PRIORITY_EMOJI.get(r.priority.value, "·")
        emoji_k = _KIND_EMOJI.get(r.kind.value, "·")
        lines.append(
            f"\n### {emoji_k} {r.title}  _({emoji_p} `{r.priority.value}`, "
            f"`{r.kind.value}`)_"
        )
        lines.append(f"- **Por qué**: {r.rationale}")
        lines.append(f"- **Acción sugerida**: {r.suggested_action}")
        if r.evidence_refs:
            lines.append(
                "- **Evidencia**: " + ", ".join(f"`{e}`" for e in r.evidence_refs)
            )
    return "\n".join(lines)


def _render_next_actions(pack: OptimizationRecommendationPack) -> str:
    if not pack.next_actions:
        return ""
    lines = ["## 06. Próximas acciones"]
    for a in pack.next_actions:
        lines.append(f"- {a}")
    return "\n".join(lines)


def _render_footer(pack: OptimizationRecommendationPack) -> str:
    return (
        "---\n\n"
        f"_Generated by `core.analytics.analyzer` v1 "
        f"(`{pack.contract_version}`). Heurísticas deterministas; sin LLM, "
        "sin API externa, sin GA4 / Ads / Search Console. Solo análisis "
        "local de datos importados._"
    )


# Make the kinds importable from the renderer for tests, even
# though they are re-exported from models.
__all__ = [
    "RecommendationKind",
    "RecommendationPriority",
    "render_markdown_import_report",
    "render_markdown_recommendations",
]
