"""Renderer tests — the markdown pack must contain the structural sections."""

from __future__ import annotations

from pathlib import Path

import pytest

from core.approval import (
    ApprovalPackBuilder,
    render_markdown_pack,
)
from core.memory import JsonFileMemory
from core.strategy import StrategyPipeline

REPO_ROOT = Path(__file__).resolve().parents[2]
DEMO_BRIEF = REPO_ROOT / "examples" / "clients" / "demo-saas" / "brief.json"


@pytest.fixture
def mem(tmp_path: Path) -> JsonFileMemory:
    return JsonFileMemory(tmp_path)


@pytest.fixture
def demo_pack(mem: JsonFileMemory):
    pipeline = StrategyPipeline(memory=mem)
    report = pipeline.run_from_path(DEMO_BRIEF).report
    builder = ApprovalPackBuilder(memory=mem)
    return builder.build_from_report(report)


@pytest.fixture
def risky_pack(mem: JsonFileMemory):
    pipeline = StrategyPipeline(memory=mem)
    report = pipeline.run_from_path(DEMO_BRIEF).report
    # Inject claims into the report to exercise the detection table.
    report = report.model_copy(deep=True)
    report.value_proposition.headline = (
        "Te aseguramos resultados garantizados sin riesgo"
    )
    report.email_sequence.emails[0].subject = "Solo hoy"
    builder = ApprovalPackBuilder(memory=mem)
    return builder.build_from_report(report)


# ---------- structural sections present ----------

_SECTION_TITLES = [
    "01. Resumen",
    "02. Estado del pack",
    "03. Claims detectados",
    "04. Checklist para el reviewer",
    "05. Decisión humana",
]


@pytest.mark.parametrize("title", _SECTION_TITLES)
def test_section_header_present(demo_pack, title: str) -> None:
    md = render_markdown_pack(demo_pack)
    assert f"## {title}" in md


def test_top_level_header(demo_pack) -> None:
    md = render_markdown_pack(demo_pack)
    assert md.startswith("# Approval Pack — demo-saas")


def test_pack_contract_in_header(demo_pack) -> None:
    md = render_markdown_pack(demo_pack)
    assert "approval-pack.v1" in md


def test_footer_present(demo_pack) -> None:
    md = render_markdown_pack(demo_pack)
    assert "Generated by `core.approval` engine v1" in md


# ---------- clean pack content ----------

def test_clean_pack_says_zero_detections(demo_pack) -> None:
    md = render_markdown_pack(demo_pack)
    assert "Total detecciones**: 0" in md
    assert "no se detectaron claims sensibles" in md


def test_clean_pack_not_blocking(demo_pack) -> None:
    md = render_markdown_pack(demo_pack)
    assert "Bloquea publicación**: ✅ `False`" in md


def test_clean_pack_no_decision_yet(demo_pack) -> None:
    md = render_markdown_pack(demo_pack)
    assert "sin decisión registrada" in md


# ---------- risky pack content ----------

def test_risky_pack_has_blockers(risky_pack) -> None:
    md = render_markdown_pack(risky_pack)
    assert "🛑" in md
    assert "[blocker]" in md


def test_risky_pack_blocks_publish(risky_pack) -> None:
    md = render_markdown_pack(risky_pack)
    assert "Bloquea publicación**: 🛑 `True`" in md


def test_risky_pack_lists_detections_table(risky_pack) -> None:
    md = render_markdown_pack(risky_pack)
    assert "| Severidad | Categoría | Ubicación | Span | Mitigación |" in md
    # The unsafe garantizado detection should appear in the table.
    assert "garantizado" in md or "guaranteed_outcome" in md


def test_risky_pack_includes_per_detection_detail(risky_pack) -> None:
    md = render_markdown_pack(risky_pack)
    assert "### Detalle por detección" in md
    assert "**Mitigación sugerida**" in md


# ---------- determinism ----------

def test_renderer_is_pure(demo_pack) -> None:
    a = render_markdown_pack(demo_pack)
    b = render_markdown_pack(demo_pack)
    assert a == b


# ---------- decision section ----------

def test_decision_section_after_approve(mem: JsonFileMemory) -> None:
    pipeline = StrategyPipeline(memory=mem)
    report = pipeline.run_from_path(DEMO_BRIEF).report
    builder = ApprovalPackBuilder(memory=mem)
    pack = builder.build_from_report(report)
    builder.persist(pack)
    approved = builder.approve(
        report.client_slug, pack.pack_id, reviewer="lucas", notes="vamos",
    )
    md = render_markdown_pack(approved)
    assert "Reviewer**: `lucas`" in md
    assert "vamos" in md
