"""Renderer tests for the campaign run summary."""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from pathlib import Path

import pytest

from core.memory import JsonFileMemory
from core.pipeline import (
    CampaignRunSummary,
    PipelineOrchestrator,
    StageId,
    StageOutcome,
    StageResult,
    render_markdown_summary,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
DEMO_INTAKE = REPO_ROOT / "examples" / "intake" / "demo-business.json"


@pytest.fixture
def real_summary(tmp_path: Path) -> CampaignRunSummary:
    mem = JsonFileMemory(tmp_path / "mem")
    orch = PipelineOrchestrator(memory=mem, outputs_root=tmp_path / "out")
    return orch.run_from_file(DEMO_INTAKE)


_SECTION_TITLES = [
    "01. Resumen",
    "02. Stages",
    "03. Artefactos producidos",
    "04. Próximos pasos",
]


@pytest.mark.parametrize("title", _SECTION_TITLES)
def test_section_header_present(real_summary, title: str) -> None:
    md = render_markdown_summary(real_summary)
    assert f"## {title}" in md


def test_top_level_header(real_summary) -> None:
    md = render_markdown_summary(real_summary)
    assert md.startswith("# Campaign Pipeline Run — acme-bootstrapped")


def test_footer_present(real_summary) -> None:
    md = render_markdown_summary(real_summary)
    assert "Generated by `core.pipeline` orchestrator v1" in md
    assert "No image was generated" in md
    assert "No piece was published" in md


def test_pipeline_contract_in_header(real_summary) -> None:
    md = render_markdown_summary(real_summary)
    assert "pipeline-run.v1" in md


def test_stages_table_rendered(real_summary) -> None:
    md = render_markdown_summary(real_summary)
    assert "| Stage | Outcome | Duración (s) | Notas |" in md


def test_all_six_stages_rendered(real_summary) -> None:
    md = render_markdown_summary(real_summary)
    for stage in ("intake", "strategy", "approval", "creative", "visual", "summary"):
        assert f"`{stage}`" in md


def test_pack_ids_rendered(real_summary) -> None:
    md = render_markdown_summary(real_summary)
    assert "Pack IDs" in md
    assert "approval_pack_id" in md
    assert "creative_pack_id" in md
    assert "visual_pack_id" in md


def test_clean_summary_says_no_block(real_summary) -> None:
    md = render_markdown_summary(real_summary)
    assert "Bloquea publicación**: ✅ `False`" in md


def test_next_steps_for_draft_pack(real_summary) -> None:
    md = render_markdown_summary(real_summary)
    assert "Próximos pasos" in md
    # Draft (clean) summary → draft hint.
    assert "draft" in md or "Pack en draft" in md


def test_renderer_is_pure(real_summary) -> None:
    a = render_markdown_summary(real_summary)
    b = render_markdown_summary(real_summary)
    assert a == b


def test_synthetic_blocked_summary_shows_block() -> None:
    """Hand-built summary with blocked semantics renders the block."""
    now = datetime(2026, 5, 30, 12, 0, tzinfo=UTC)
    later = now + timedelta(seconds=5)
    stages = [
        StageResult(
            stage_id=StageId.INTAKE,
            outcome=StageOutcome.SUCCEEDED,
            started_at=now,
            finished_at=later,
        ),
        StageResult(
            stage_id=StageId.APPROVAL,
            outcome=StageOutcome.BLOCKED,
            started_at=now,
            finished_at=later,
        ),
    ]
    s = CampaignRunSummary(
        client_slug="demo-co",
        started_at=now,
        finished_at=later,
        overall_state="blocked",
        blocks_publish=True,
        intake_critical_count=0,
        intake_warning_count=0,
        intake_info_count=0,
        stages=stages,
    )
    md = render_markdown_summary(s)
    assert "🛑" in md
    assert "Bloquea publicación**: 🛑 `True`" in md
