"""Renderer tests — sections + content + purity."""

from __future__ import annotations

from pathlib import Path

import pytest

from core.approval import ApprovalPackBuilder
from core.memory import JsonFileMemory
from core.strategy import StrategyPipeline
from core.visual import VisualPromptFactory, render_markdown_pack

REPO_ROOT = Path(__file__).resolve().parents[2]
DEMO_BRIEF = REPO_ROOT / "examples" / "clients" / "demo-saas" / "brief.json"


@pytest.fixture
def mem(tmp_path: Path) -> JsonFileMemory:
    return JsonFileMemory(tmp_path)


@pytest.fixture
def report(mem: JsonFileMemory):
    return StrategyPipeline(memory=mem).run_from_path(DEMO_BRIEF).report


@pytest.fixture
def clean_pack(mem: JsonFileMemory, report):
    builder = ApprovalPackBuilder(memory=mem)
    pack = builder.build_from_report(report)
    builder.persist(pack)
    return VisualPromptFactory(memory=mem).build(
        report, builder.load(report.client_slug, pack.pack_id), None
    )


@pytest.fixture
def blocking_pack(mem: JsonFileMemory, report):
    risky = report.model_copy(deep=True)
    risky.value_proposition.headline = (
        "Te aseguramos resultados garantizados sin riesgo"
    )
    builder = ApprovalPackBuilder(memory=mem)
    ap = builder.build_from_report(risky)
    return VisualPromptFactory(memory=mem).build(risky, ap, None)


_SECTION_TITLES = [
    "01. Resumen",
    "02. Style Guide de campaña",
    "03. Direcciones por pieza",
    "04. Riesgos visuales globales",
    "05. Checklist global",
]


@pytest.mark.parametrize("title", _SECTION_TITLES)
def test_section_header_present(clean_pack, title: str) -> None:
    md = render_markdown_pack(clean_pack)
    assert f"## {title}" in md


def test_top_level_header(clean_pack) -> None:
    md = render_markdown_pack(clean_pack)
    assert md.startswith("# Visual Direction Pack — demo-saas")


def test_footer_present(clean_pack) -> None:
    md = render_markdown_pack(clean_pack)
    assert "Generated by `core.visual` engine v1" in md
    assert "no PNG/JPG is produced" in md
    assert "Terminal positive state is `ready_for_publish`" in md


def test_pack_contract_in_header(clean_pack) -> None:
    md = render_markdown_pack(clean_pack)
    assert "visual-direction-pack.v1" in md


# ---------- summary content ----------

def test_clean_pack_summary_shows_no_block(clean_pack) -> None:
    md = render_markdown_pack(clean_pack)
    assert "Bloquea publicación**: ✅ `False`" in md


def test_blocking_pack_summary_shows_block(blocking_pack) -> None:
    md = render_markdown_pack(blocking_pack)
    assert "Bloquea publicación**: 🛑 `True`" in md


def test_blocking_pack_directions_are_blocked(blocking_pack) -> None:
    md = render_markdown_pack(blocking_pack)
    assert "🛑 `blocked`" in md


# ---------- style guide content ----------

def test_style_guide_renders_palette(clean_pack) -> None:
    md = render_markdown_pack(clean_pack)
    assert "Paleta primaria" in md


def test_style_guide_renders_typography(clean_pack) -> None:
    md = render_markdown_pack(clean_pack)
    assert "Tipografía headline" in md
    assert "Tipografía body" in md


# ---------- directions content ----------

def test_all_11_piece_types_rendered(clean_pack) -> None:
    md = render_markdown_pack(clean_pack)
    for label in [
        "instagram_post",
        "instagram_story",
        "instagram_carousel",
        "linkedin_post_graphic",
        "facebook_post",
        "reels_cover",
        "email_header",
        "landing_hero",
        "ad_creative",
        "flyer_square",
        "flyer_vertical",
    ]:
        assert label in md


def test_variants_rendered(clean_pack) -> None:
    md = render_markdown_pack(clean_pack)
    # Both variant IDs appear.
    assert "Variant A" in md
    assert "Variant B" in md


def test_each_direction_has_full_prompt(clean_pack) -> None:
    md = render_markdown_pack(clean_pack)
    assert "**Prompt completo**" in md
    assert "**Negative prompt**:" in md


def test_per_direction_checklist_rendered(clean_pack) -> None:
    md = render_markdown_pack(clean_pack)
    assert "Checklist del piece type" in md


# ---------- risks content ----------

def test_risks_table_rendered(clean_pack) -> None:
    md = render_markdown_pack(clean_pack)
    assert "| Severidad | Categoría | Descripción | Mitigación |" in md


# ---------- global checklist content ----------

def test_global_checklist_rendered(clean_pack) -> None:
    md = render_markdown_pack(clean_pack)
    assert "Checklist global" in md
    assert "[must]" in md


# ---------- never published ----------

def test_no_published_token_in_markdown(clean_pack, blocking_pack) -> None:
    for pack in (clean_pack, blocking_pack):
        md = render_markdown_pack(pack)
        assert "`published`" not in md
        assert "` published`" not in md


# ---------- determinism ----------

def test_renderer_is_pure(clean_pack) -> None:
    a = render_markdown_pack(clean_pack)
    b = render_markdown_pack(clean_pack)
    assert a == b
