"""Markdown renderer for the n8n execution dry-run payload (MKT-5C).

Pure function. Same payload → same Markdown.
"""

from __future__ import annotations

import json

from .models import (
    N8nActionStatus,
    N8nActionType,
    N8nExecutionPayload,
)

_STATUS_EMOJI: dict[str, str] = {
    "planned": "🟢",
    "blocked": "🛑",
    "skipped": "⏭️",
    "dispatched": "✅",
    "failed": "💥",
}

_TYPE_ORDER: list[N8nActionType] = [
    N8nActionType.CAMPAIGN_REPORT_NOTIFICATION,
    N8nActionType.TELEGRAM_NOTIFICATION,
    N8nActionType.DRIVE_ASSET_FOLDER,
    N8nActionType.NOTION_STATUS_UPDATE,
    N8nActionType.EMAIL_DRAFT,
    N8nActionType.SOCIAL_POST_DRAFT,
]


def render_markdown_payload(payload: N8nExecutionPayload) -> str:
    parts: list[str] = []
    parts.append(_render_header(payload))
    parts.append(_render_summary(payload))
    for kind in _TYPE_ORDER:
        section = _render_section(payload, kind)
        if section:
            parts.append(section)
    parts.append(_render_footer(payload))
    return "\n\n".join(parts) + "\n"


def _render_header(payload: N8nExecutionPayload) -> str:
    return (
        f"# n8n Execution Payload — {payload.client_slug} _(DRY RUN)_\n\n"
        f"- **Payload ID**: `{payload.payload_id}`\n"
        f"- **Contract**: `{payload.contract_version}`\n"
        f"- **Rule set**: `{payload.rule_set_id or '—'}`\n"
        f"- **Run summary**: `{payload.run_summary_id or '—'}`\n"
        f"- **Task pack**: `{payload.task_pack_id or '—'}`\n"
        f"- **Creative pack**: `{payload.creative_pack_id or '—'}`\n"
        f"- **Visual pack**: `{payload.visual_pack_id or '—'}`\n"
        f"- **Notion sync report**: `{payload.notion_sync_report_id or '—'}`\n"
        f"- **Generado**: `{payload.created_at.isoformat()}`\n\n"
        "> ⚠️ Esto es un dry-run. No se llamó a n8n, no se "
        "disparó ningún webhook, no se leyó ningún URL de "
        "webhook, no se envió ningún email ni mensaje."
    )


def _render_summary(payload: N8nExecutionPayload) -> str:
    s = payload.stats
    blocks_emoji = "🛑" if payload.blocks_publish else "✅"
    lines = ["## 01. Resumen"]
    lines.append(f"- **Total acciones**: `{s.total_actions}`")
    lines.append(
        f"- **Bloquea publicación**: {blocks_emoji} `{payload.blocks_publish}`"
    )
    lines.append(f"- 🟢 `planned`: {s.planned}")
    lines.append(f"- 🛑 `blocked`: {s.blocked}")
    lines.append("\n**Por tipo de acción**:")
    for kind in _TYPE_ORDER:
        c = s.by_type.get(kind.value, 0)
        if c:
            lines.append(f"- `{kind.value}`: {c}")
    return "\n".join(lines)


def _render_section(payload: N8nExecutionPayload, kind: N8nActionType) -> str:
    actions = payload.actions_of_type(kind)
    if not actions:
        return ""
    lines = [f"## {kind.value} ({len(actions)})"]
    # Sort: blocked first, then by source_ref for stability.
    actions_sorted = sorted(
        actions,
        key=lambda a: (
            0 if a.status is N8nActionStatus.BLOCKED else 1,
            a.source_ref or "",
        ),
    )
    lines.append("| # | Estado | Webhook | Source | Razón |")
    lines.append("|---|--------|---------|--------|-------|")
    for i, a in enumerate(actions_sorted, start=1):
        emoji = _STATUS_EMOJI.get(a.status.value, "·")
        webhook = f"`{a.target_webhook}`"
        src = f"`{a.source_kind or '—'}` {(a.source_ref or '')[:20]}".strip()
        reason = (a.blocked_reason or "—").replace("|", "\\|")[:80]
        lines.append(
            f"| {i} | {emoji} `{a.status.value}` | {webhook} | {src} | {reason} |"
        )
    # Sample payload for the first action (truncated).
    sample = actions_sorted[0].payload
    if sample:
        sample_json = json.dumps(sample, ensure_ascii=False, indent=2)
        if len(sample_json) > 800:
            sample_json = sample_json[:800] + "\n  ...(truncado)"
        lines.append("\n**Ejemplo de payload (primera acción)**:")
        lines.append(f"```json\n{sample_json}\n```")
    return "\n".join(lines)


def _render_footer(payload: N8nExecutionPayload) -> str:
    return (
        "---\n\n"
        f"_Generated by `core.n8n_sync` v1 (`{payload.contract_version}`). "
        "Deterministic dry-run. **No HTTP call was made. No webhook URL "
        "was read. No email, message or asset was sent or created.** "
        "El bloque real de sync a n8n (con webhook URLs reales) es scope "
        "de un bloque futuro._"
    )


__all__ = ["render_markdown_payload"]
