"""Renderer tests — sections + content + purity."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from core.intake import (
    ClientIntake,
    IntakeValidator,
    render_intake_summary,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
DEMO = REPO_ROOT / "examples" / "intake" / "demo-business.json"


@pytest.fixture
def demo_intake() -> ClientIntake:
    return ClientIntake.model_validate(
        json.loads(DEMO.read_text(encoding="utf-8"))
    )


@pytest.fixture
def demo_validation(demo_intake: ClientIntake):
    return IntakeValidator().validate(demo_intake)


@pytest.fixture
def critical_intake() -> ClientIntake:
    return ClientIntake(client_name="Acme")  # missing everything important


@pytest.fixture
def critical_validation(critical_intake: ClientIntake):
    return IntakeValidator().validate(critical_intake)


_SECTION_TITLES = [
    "01. Estado del intake",
    "02. Warnings / datos faltantes",
    "03. Resumen del intake recibido",
    "04. Defaults operacionales aplicados",
]


@pytest.mark.parametrize("title", _SECTION_TITLES)
def test_section_header_present(demo_intake, demo_validation, title: str) -> None:
    md = render_intake_summary(demo_intake, demo_validation)
    assert f"## {title}" in md


def test_top_level_header(demo_intake, demo_validation) -> None:
    md = render_intake_summary(demo_intake, demo_validation)
    assert md.startswith("# Client Brief Intake — Acme Bootstrapped")


def test_footer_present(demo_intake, demo_validation) -> None:
    md = render_intake_summary(demo_intake, demo_validation)
    assert "Generated by `core.intake` engine v1" in md
    assert "no data fabrication" in md


def test_clean_intake_shows_valid(demo_intake, demo_validation) -> None:
    md = render_intake_summary(demo_intake, demo_validation)
    assert "Valid**: ✅ `True`" in md
    assert "Can normalize → brief**: ✅ `True`" in md


def test_critical_intake_shows_invalid(critical_intake, critical_validation) -> None:
    md = render_intake_summary(critical_intake, critical_validation)
    assert "Valid**: 🛑 `False`" in md
    assert "Brief NO se puede generar todavía" in md


def test_warnings_table_present(critical_intake, critical_validation) -> None:
    md = render_intake_summary(critical_intake, critical_validation)
    assert "| Severidad | Campo | Mensaje | Acción sugerida |" in md
    assert "🛑 `critical`" in md


def test_clean_intake_says_no_warnings(demo_intake, demo_validation) -> None:
    md = render_intake_summary(demo_intake, demo_validation)
    # The demo brief is complete so no warnings.
    assert "_(sin warnings)_" in md


def test_intake_recap_lists_competitors(demo_intake, demo_validation) -> None:
    md = render_intake_summary(demo_intake, demo_validation)
    assert "Big Marketing Suite" in md
    assert "Quick MKT" in md


def test_intake_recap_lists_brand_tone(demo_intake, demo_validation) -> None:
    md = render_intake_summary(demo_intake, demo_validation)
    assert "- claro" in md
    assert "- directo" in md
    assert "- irreverente" in md


def test_defaults_section_lists_applied(critical_intake, critical_validation) -> None:
    md = render_intake_summary(critical_intake, critical_validation)
    assert "Defaults operacionales aplicados" in md
    # The critical intake is missing operational fields → defaults appear.
    assert "duration_weeks" in md
    assert "primary_kpi" in md
    assert "locale" in md


def test_renderer_is_pure(demo_intake, demo_validation) -> None:
    a = render_intake_summary(demo_intake, demo_validation)
    b = render_intake_summary(demo_intake, demo_validation)
    assert a == b


def test_renderer_mentions_next_step_when_normalizable(
    demo_intake, demo_validation
) -> None:
    md = render_intake_summary(demo_intake, demo_validation)
    assert "mkt run-strategy --brief" in md
