"""Renderer tests — sections present, content correct, pure."""

from __future__ import annotations

from pathlib import Path

import pytest

from core.approval import ApprovalPackBuilder
from core.creative import CreativeFactory, render_markdown_pack
from core.memory import JsonFileMemory
from core.strategy import StrategyPipeline

REPO_ROOT = Path(__file__).resolve().parents[2]
DEMO_BRIEF = REPO_ROOT / "examples" / "clients" / "demo-saas" / "brief.json"


@pytest.fixture
def mem(tmp_path: Path) -> JsonFileMemory:
    return JsonFileMemory(tmp_path)


@pytest.fixture
def report(mem: JsonFileMemory):
    return StrategyPipeline(memory=mem).run_from_path(DEMO_BRIEF).report


@pytest.fixture
def clean_pack(mem: JsonFileMemory, report):
    builder = ApprovalPackBuilder(memory=mem)
    builder.persist(builder.build_from_report(report))
    return CreativeFactory(memory=mem).build(report, builder.load(report.client_slug))


@pytest.fixture
def blocking_pack(mem: JsonFileMemory, report):
    risky = report.model_copy(deep=True)
    risky.value_proposition.headline = (
        "Te aseguramos resultados garantizados sin riesgo"
    )
    builder = ApprovalPackBuilder(memory=mem)
    ap = builder.build_from_report(risky)
    return CreativeFactory(memory=mem).build(risky, ap)


# ---------- structural sections ----------

_SECTION_TITLES = [
    "01. Resumen",
    "02. Calendario sugerido",
    "03. Social posts",
    "04. Emails",
    "05. Reels",
    "06. Flyers copy",
    "07. Prompts para imágenes",
]


@pytest.mark.parametrize("title", _SECTION_TITLES)
def test_section_header_present(clean_pack, title: str) -> None:
    md = render_markdown_pack(clean_pack)
    assert f"## {title}" in md


def test_top_level_header(clean_pack) -> None:
    md = render_markdown_pack(clean_pack)
    assert md.startswith("# Creative Asset Pack — demo-saas")


def test_footer_present(clean_pack) -> None:
    md = render_markdown_pack(clean_pack)
    assert "Generated by `core.creative` engine v1" in md
    assert "terminal positive state is `ready_for_publish`" in md


def test_pack_contract_in_header(clean_pack) -> None:
    md = render_markdown_pack(clean_pack)
    assert "creative-pack.v1" in md


# ---------- content ----------

def test_clean_pack_summary_shows_zero_blocks(clean_pack) -> None:
    md = render_markdown_pack(clean_pack)
    assert "Bloquea publicación**: ✅ `False`" in md


def test_blocking_pack_summary_shows_block(blocking_pack) -> None:
    md = render_markdown_pack(blocking_pack)
    assert "Bloquea publicación**: 🛑 `True`" in md


def test_blocking_pack_assets_are_blocked(blocking_pack) -> None:
    md = render_markdown_pack(blocking_pack)
    # Every asset header should carry the blocked badge.
    assert "🛑 `blocked`" in md


def test_calendar_table_rendered(clean_pack) -> None:
    md = render_markdown_pack(clean_pack)
    assert "| Fecha | Semana | Tipo | Canal | Nota |" in md


def test_hook_variants_rendered(clean_pack) -> None:
    md = render_markdown_pack(clean_pack)
    # Variants are emitted as labelled bullets.
    assert "**Hook variants**:" in md
    assert "**A**" in md
    assert "**B**" in md


def test_subject_variants_rendered(clean_pack) -> None:
    md = render_markdown_pack(clean_pack)
    assert "**Subject variants**:" in md


def test_image_prompt_rendered(clean_pack) -> None:
    md = render_markdown_pack(clean_pack)
    assert "**Prompt**:" in md
    assert "**Negative prompt**:" in md


def test_per_asset_checklist_rendered(clean_pack) -> None:
    md = render_markdown_pack(clean_pack)
    assert "**Checklist**:" in md
    assert "[must]" in md


def test_no_published_token_in_markdown(clean_pack, blocking_pack) -> None:
    """The word `published` (en estado) nunca aparece para un asset."""
    for pack in (clean_pack, blocking_pack):
        md = render_markdown_pack(pack)
        # The badge format is `<emoji> `<state>``. We check that no asset
        # carries a `published` state by looking for that exact rendered
        # token.
        assert "` published`" not in md
        assert "`published`" not in md


# ---------- determinism ----------

def test_renderer_is_pure(clean_pack) -> None:
    a = render_markdown_pack(clean_pack)
    b = render_markdown_pack(clean_pack)
    assert a == b
