"""Markdown renderer for the Notion sync execution report (MKT-5B)."""

from __future__ import annotations

from .sync_report import NotionSyncReport, SyncMode

_OUTCOME_EMOJI: dict[str, str] = {
    "created": "✅",
    "skipped_blocked": "🛑",
    "skipped_invalid": "❌",
    "skipped_already_synced": "🔁",
    "skipped_refused": "⏸️",
    "failed": "💥",
}


def render_markdown_report(report: NotionSyncReport) -> str:
    parts: list[str] = []
    parts.append(_render_header(report))
    parts.append(_render_summary(report))
    parts.append(_render_records(report))
    parts.append(_render_footer(report))
    return "\n\n".join(parts) + "\n"


def _render_header(report: NotionSyncReport) -> str:
    mode_label = (
        "🟢 WRITE (real, confirmed)"
        if report.mode is SyncMode.WRITE and report.write_attempted
        else "⏸️ DRY-RUN"
    )
    block_warn = ""
    if report.write_blocked_reason:
        block_warn = (
            "\n\n> ⚠️ **Write requested but BLOCKED**: "
            f"{report.write_blocked_reason}\n> "
            "El sync se ejecutó como dry-run."
        )
    return (
        f"# Notion Sync Report — {report.client_slug}\n\n"
        f"- **Report ID**: `{report.report_id}`\n"
        f"- **Contract**: `{report.contract_version}`\n"
        f"- **Rule set**: `{report.rule_set_id or '—'}`\n"
        f"- **Plan**: `{report.plan_id}` ({report.plan_contract_version})\n"
        f"- **Task pack**: `{report.task_pack_id}`\n"
        f"- **Modo solicitado**: `{report.mode.value}`\n"
        f"- **Confirmado**: `{report.confirmed}`\n"
        f"- **Write efectivo**: {mode_label}\n"
        f"- **NOTION_TOKEN presente**: `{report.token_env_present}`\n"
        f"- **NOTION_TASKS_DATABASE_ID presente**: `{report.database_id_env_present}`\n"
        f"- **SDK notion-client instalado**: `{report.sdk_available}`\n"
        f"- **Iniciado**: `{report.started_at.isoformat()}`\n"
        f"- **Finalizado**: `{report.finished_at.isoformat()}`\n"
        f"- **Duración**: `{report.duration_seconds:.2f}s`"
        f"{block_warn}"
    )


def _render_summary(report: NotionSyncReport) -> str:
    s = report.stats
    lines = ["## 01. Resumen"]
    lines.append(f"- **Total de registros**: `{s.total_records}`")
    lines.append(f"- ✅ `created`: {s.created}")
    lines.append(f"- 🛑 `skipped_blocked`: {s.skipped_blocked}")
    lines.append(f"- ❌ `skipped_invalid`: {s.skipped_invalid}")
    lines.append(f"- 🔁 `skipped_already_synced`: {s.skipped_already_synced}")
    lines.append(f"- ⏸️ `skipped_refused`: {s.skipped_refused}")
    lines.append(f"- 💥 `failed`: {s.failed}")
    return "\n".join(lines)


def _render_records(report: NotionSyncReport) -> str:
    lines = ["## 02. Registros"]
    if not report.records:
        lines.append("_(sin registros)_")
        return "\n".join(lines)
    # Sort: failed first (loud), then by outcome rank, then by title.
    outcome_rank = {
        "failed": 0,
        "skipped_invalid": 1,
        "skipped_blocked": 2,
        "skipped_refused": 3,
        "skipped_already_synced": 4,
        "created": 5,
    }
    records = sorted(
        report.records,
        key=lambda r: (outcome_rank.get(r.outcome.value, 9), r.title),
    )
    lines.append("| # | Outcome | Tarea | Page ID | Error / Razón |")
    lines.append("|---|---------|-------|---------|----------------|")
    for i, r in enumerate(records, start=1):
        emoji = _OUTCOME_EMOJI.get(r.outcome.value, "·")
        title = r.title.replace("|", "\\|")[:80]
        page = (r.page_id or "—")[:24]
        reason_or_err = r.error_message or r.reason or "—"
        reason_or_err = reason_or_err.replace("|", "\\|")[:120]
        lines.append(
            f"| {i} | {emoji} `{r.outcome.value}` | {title} | `{page}` | {reason_or_err} |"
        )
    return "\n".join(lines)


def _render_footer(report: NotionSyncReport) -> str:
    note = (
        "Sync ejecutado contra Notion real."
        if report.write_attempted
        else "Dry-run. No se conectó a Notion. No se creó ninguna página."
    )
    return (
        "---\n\n"
        f"_Generated by `core.notion_sync.executor` v1 (`{report.contract_version}`). "
        f"{note} Sin update / archive / delete. Sin avance automático de estados._"
    )


__all__ = ["render_markdown_report"]
